_target_: src.models.cifar10_lit_module.CIFAR10LitModule

num_classes: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 1e-6

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 100
  eta_min: 0.00001

net:
  _target_: src.models.components.resnet.ResNet
  model_name: resnet18
  pretrained: True 
  num_classes: ${model.num_classes}